### ISSUE TITLE
Pretrained Codebooks?

### ISSUE THREAD

**Issue by oyt9306** [zbr17/OptVQ#1]
Hello. Thank you for your nice work!
I have tried to reproduce (retrain) your work and got stuck with loading the codebook from ckpt.
Is there any available learned codebook of the pre-trained models (i.e., checkpoints of 16x16x4 and 16x16x8)? 
I would like to appreciate it if you could provide the ckpt of the learned codebooks. 
Thank you!

**Comment by zbr17** [comment]
Hello,

Thank you for your interest in our research. We are pleased to provide you with two methods to load the pretrained checkpoint for the VQGAN model.

### Method 1: Downloading from Huggingface

You may utilize the following Python code to download the pretrained VQGAN model directly from Huggingface:

```python
from optvq.models.vqgan_hf import VQModelHF
model = VQModelHF.from_pretrained("BorelTHU/optvq-16x16x4")
```

### Method 2: Downloading from Tsinghua Cloud

Alternatively, you can download the model from Tsinghua Cloud using the following code snippet:

```python
from optvq.utils.init import initiate_from_config_recursively
from omegaconf import OmegaConf
import torch
config = OmegaConf.load("configs/optvq.yaml")
model = initiate_from_config_recursively(config.autoencoder)
params = torch.load("path_to_checkpoint", map_location="cpu")
model.load_state_dict(params["model"])
```

Please replace `"path_to_checkpoint"` with the actual path to your checkpoint file.

---

After successfully loading the checkpoints using either of the above methods, you can extract the codebook parameters as follows:

```python
# Retrieve the codebook
codebook = model.quantize.embedding.weight
# Or save it to a file
torch.save(codebook, "path_to_save_codebook")
```

Replace `"path_to_save_codebook"` with the desired file path for saving the codebook.

For your convenience, we have uploaded the codebook (16x16x4 version) parameters to Tsinghua Cloud with filename as [code.pth](https://cloud.tsinghua.edu.cn/d/91befd96f06a4a83bb03/).

---

Given the close relationship between the codebook and both the encoder and decoder, we strongly recommend loading the entire set of parameters for optimal results.

Should you encounter any issues or require further clarification, please do not hesitate to reach out.

**Comment by oyt9306** [comment]
Thank you for your prompt and kind responses! 🙂
